name: Release

on:
  # Run the workflow each time new commits are pushed to the candidate branch.
  push:
    branches: [ "candidate", "core24" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write

jobs:
  get-architectures:
    name: ðŸ–¥ Get snap architectures
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.get-architectures.outputs.architectures }}
      architectures-list: ${{ steps.get-architectures.outputs.architectures-list }}
    steps:
      - name: ðŸ–¥ Get snap architectures
        id: get-architectures
        uses: snapcrafters/ci/get-architectures@main

  release:
    name: ðŸš¢ Release to latest/candidate
    needs: get-architectures
    runs-on: ubuntu-latest
    environment: "Candidate Branch"
    strategy:
      fail-fast: false
      matrix:
        architecture: ${{ fromJSON(needs.get-architectures.outputs.architectures-list) }}
    steps:
      - name: Detect channel
        id: get_channel
        run: |
          if [[ $GITHUB_REF_NAME == "core24" ]]; then
            echo "channel=beta/core24" >> $GITHUB_OUTPUT
          else
            echo "channel=candidate" >> $GITHUB_OUTPUT
          fi
      - name: ðŸš¢ Release to latest/candidate
        uses: snapcrafters/ci/release-to-candidate@main
        with:
          channel: ${{ steps.get_channel.outputs.channel }}
          architecture: ${{ matrix.architecture }}
          launchpad-token: ${{ secrets.LP_BUILD_SECRET }}
          repo-token: ${{ secrets.SNAPCRAFTERS_BOT_COMMIT }}
          store-token: ${{ secrets.SNAP_STORE_CANDIDATE }}

  call-for-testing:
    name: ðŸ“£ Create call for testing
    needs: [release, get-architectures]
    environment: "Candidate Branch"
    runs-on: ubuntu-latest
    outputs:
      issue-number: ${{ steps.issue.outputs.issue-number }}
    steps:
      - name: ðŸ“£ Create call for testing
        id: issue
        uses: snapcrafters/ci/call-for-testing@main
        with:
          architectures: ${{ needs.get-architectures.outputs.architectures }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  # Commented out because this is a CLI app.
  # screenshots:
  #   name: ðŸ“¸ Gather screenshots
  #   needs: call-for-testing
  #   environment: "Candidate Branch"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: ðŸ“¸ Gather screenshots
  #       uses: snapcrafters/ci/get-screenshots@main
  #       with:
  #         issue-number: ${{ needs.call-for-testing.outputs.issue-number }}
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         screenshots-token: ${{ secrets.SNAPCRAFTERS_BOT_COMMIT }}
